name: 'Build LaTex Document'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic main.tex
      - name: Run Tectonic on solutions/main.tex
        run: tectonic solutions/main.tex -o solutions.pdf
      - name: Upload pdfs
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: out/*/*.pdf
